#!/usr/bin/env bash

views=('roads_z10' 'roads_z11' 'roads_z12'
       'roads_z13' 'roads_z14' 'roads_z15plus'
       'roads_z15plus_small' 'roads_z15plus_big')

setup() {
    psql $@ -f high_road_views-setup.pgsql

    create_matviews=$(for name in "${views[@]}"; do
                          echo "SELECT create_matview('${name}_mv', '$name');"
                      done)
    echo $create_matviews | psql $@

    create_indexes=$(for name in "${views[@]}"; do
                         echo "CREATE INDEX ${name}_mv_way_idx ON ${name}_mv USING GIST(way);"
                     done)
    echo $create_indexes | psql $@
}

remove() {
    remove_matviews=$(for name in "${views[@]}"; do
                          echo "SELECT drop_matview('${name}_mv');"
                      done)
    echo $remove_matviews | psql $@

    psql $@ -f high_road_views-remove.pgsql
}
